---
- name: Configure the login banner
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: Add configure the login banner
      ios_banner:
    #You can change below value to (motd, login, incoming or slip-ppp)
        banner: login
        text: |
              ________________________________________________________
          
                                    AVISO IMPORTANTE !!                          
                                                                                 
               Antes de aplicar qualquer modificacao na configuracao tenha       
              certeza de que a mesma nao trara nenhum impacto para o ambiente    
                                                                                 
                     Ao final de qualquer modificacao lembre de SALVAR           
                                                                                 
                                    TI INFRA LOJAS MM                            
                                                                                 
              ________________________________________________________                            
        state: present

    #Tasks that save running-config to start-config when modified. 
    - name: save running to start-config when modified
      ios_config:
    #You can change below value to (always,never or changed)
        save_when: modified
        
#End of codes
