---
- hosts: all
  become: true
  tasks:

    - name: Download zabbix Agent2 Conf
      ansible.builtin.get_url:
        url: http://ocs.lojasmm.com.br/download/zabbix/zabbix_agent2.conf
        dest: /opt/zabbix_agent2.conf
        mode: '0440'

    - name: Download zabbix Agent2 CentOS 7
      ansible.builtin.get_url:
        url: https://repo.zabbix.com/zabbix/6.3/rhel/7/x86_64/zabbix-agent2-6.4.0-beta6.release1.el7.x86_64.rpm
        dest: /opt/zabbix-agent2_x86_64.rpm
        mode: '0440'

    - name: Disable service zabbix-agent 
      ansible.builtin.service:
        name: zabbix-agent
        state: stopped

    - name: Disable systemctl zabbix-agent 
      ansible.builtin.systemd:
        name: zabbix-agent
        enabled: no

    - name: Remove zabbix-agent package
      ansible.builtin.yum:
        name: zabbix-agent
        state: absent
        autoremove: yes
        purge: yes

    - name: Install zabbix Agent2 rpm from a local file
      ansible.builtin.yum:
        name: /opt/zabbix-agent2_x86_64.rpm
        state: present

    - name: Enable systemctl zabbix-agent2 
      ansible.builtin.systemd:
        name: zabbix-agent2
        enabled: yes

    - name: Enable service zabbix-agent2 
      ansible.builtin.service:
        name: zabbix-agent2
        state: started
    

    - name: Copiar template de configuração pronto zabbix agent2
      ansible.builtin.shell:
        cmd: 
          mv /opt/zabbix_agent2.conf /etc/zabbix/
    
    
    - name: Restart service zabbix-agent2, in all cases
      ansible.builtin.service:
        name: zabbix-agent2
        state: restarted
