---
- name: Create a user on Switch Cisco
  hosts: all
  gather_facts: no

  vars:
    privilege: 1

  tasks:
    - name: Create a user
      ios_command:
        commands:
          - "config"
          - "username {{ username }} password {{ newpassword }} privilege {{ privilege }}"
          - "exit"
          
    - name: Save running to startup when modified
      cisco.ios.ios_config:
        save_when: always

      
      
     
