---
- name: Set admin password
  hosts: all
  gather_facts: no

  tasks:
    - name: Troca de senha admin
      ios_command:
        commands: 
          - config
          - enable password level 15 "{{ new_password }}"
          - "exit"

    - name: Save running to startup when modified
      cisco.ios.ios_config:
        save_when: always
